---
title: "Works Cited"
---


1. Biocybernetics - Wikipedia, accessed May 6, 2025, https://en.wikipedia.org/wiki/Biocybernetics
2. What is Cybernetics? Definition, history, and applications - DataScientest, accessed May 6, 2025, https://datascientest.com/en/all-about-cybernetics
3. vce.usc.edu, accessed May 6, 2025, https://vce.usc.edu/volume-7-issue-1/consciousness-and-the-self-a-philosophical-discussion-of-the-future-of-whole-brain-emulation/#:~:text=Whole%20brain%20emulation%20is%20the,cure%20neurological%20illnesses%20and%20conditions.
4. Consciousness and the Self: A Philosophical Discussion of the Future of Whole Brain Emulation - Viterbi Conversations in Ethics, accessed May 6, 2025, https://vce.usc.edu/volume-7-issue-1/consciousness-and-the-self-a-philosophical-discussion-of-the-future-of-whole-brain-emulation/
5. Whole Brain Emulation - LessWrong, accessed May 6, 2025, https://www.lesswrong.com/w/whole-brain-emulation
6. Mind uploading - Wikipedia, accessed May 6, 2025, https://en.wikipedia.org/wiki/Mind_uploading
7. How Could Whole Brain Emulation Affect Us? - Carboncopies ..., accessed May 6, 2025, https://carboncopies.org/Blog/Posts/WBEHowCouldItAffectUs/Post/
8. Connecting the Brain to Itself through an Emulation - PMC, accessed May 6, 2025, https://pmc.ncbi.nlm.nih.gov/articles/PMC5492113/
9. (PDF) The Prospects of Whole Brain Emulation within the next Half- Century - ResearchGate, accessed May 6, 2025, https://www.researchgate.net/publication/269477453_The_Prospects_of_Whole_Brain_Emulation_within_the_next_Half-_Century
10. Biocybernetics and Biomedical Engineering - Current Trends and ..., accessed May 6, 2025, https://www.kulturkaufhaus.de/web/en/detail/ISBN-2244030596258/Pijanowska-Dorota-G./Biocybernetics-and-Biomedical-Engineering---Current-Trends-and-Challenges?CSPCHD=0a1000000000V96wpuISUNmaQi5KozQaEqbRb3VvuZtYGUVu0E&bpmctrl=bpmrownr.6%3A5%7Cforeign.493987-34-5-494401%3A502001%3A400388
11. Computational neuroscience FAQ - Rajan Lab, accessed May 6, 2025, https://www.rajanlab.com/faq
12. Bioinformatics Software Engineer - Edmates, accessed May 6, 2025, https://www.edmates.com/career-guide/bioinformatics-software-engineer/
13. Cybernetics - Wikipedia, accessed May 6, 2025, https://en.wikipedia.org/wiki/Cybernetics
14. Homeostatic Systems, Biocybernetics, and Autonomic Neuroscience - PubMed Central, accessed May 6, 2025, https://pmc.ncbi.nlm.nih.gov/articles/PMC5819891/
15. BIOCYBERNETICS AND SURVIVAL - Zygon: Journal of Religion and Science, accessed May 6, 2025, https://www.zygonjournal.org/article/14989/galley/30355/download/
16. Biocybernetics - NTNU, accessed May 6, 2025, https://www.ntnu.edu/itk/research/biocybernetics
17. Taksha Center for BioCybernetics (TCBC) ⋆ Taksha Institute, accessed May 6, 2025, https://taksha.org/divisions/tcbc
18. Connecting the Brain to Itself through an Emulation - Frontiers, accessed May 6, 2025, https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2017.00373/full
19. A look back on the BRAIN Initiative in 2024 (and what's coming in 2025!), accessed May 6, 2025, https://www.braininitiative.org/achievements/a-look-back-on-the-brain-initiative-in-2024-and-whats-coming-in-2025/
20. Biocybernetics and Biomedical Engineering – Current Trends, accessed May 6, 2025, https://medicebooks.com/product/biocybernetics-and-biomedical-engineering/
21. Cybernetics and Systems Biology Laboratories | University of Stavanger, accessed May 6, 2025, https://www.uis.no/en/research/stavanger-ai-lab/information-technology/cybernetics-and-systems-biology-laboratories
22. ASC: Links: Centers & Institutes - American Society for Cybernetics, accessed May 6, 2025, https://asc-cybernetics.org/links/centers.htm
23. Home - Max-Planck-Gesellschaft, accessed May 6, 2025, https://www.kyb.tuebingen.mpg.de/en
24. Biocybernetics and Biomedical Engineering - Scimago, accessed May 6, 2025, https://www.scimagojr.com/journalsearch.php?q=19400158663&tip=sid&clean=0
25. Biocybernetics and Biomedical Engineering - Scimago, accessed May 6, 2025, https://www.scimagojr.com/journalsearch.php?q=19400158663&tip=sid
26. Engineering, Biomedical: Journal Rankings - OOIR, accessed May 6, 2025, https://ooir.org/journals.php?field=Clinical+Medicine&category=Engineering%2C+Biomedical
27. Journal Rankings on Biomedical Engineering - Scimago, accessed May 6, 2025, https://www.scimagojr.com/journalrank.php?category=2204
28. Biomedical Technology - Google Scholar Metrics, accessed May 6, 2025, https://scholar.google.com/citations?view_op=top_venues&hl=en&vq=eng_biomedicaltechnology
29. Engineering, Biomedical: Journal Rankings - OOIR, accessed May 6, 2025, https://ooir.org/journals.php?field=Engineering&category=Engineering%2C+Biomedical
30. Comment in Nature Reviews: Whole-brain modelling as an essential ..., accessed May 6, 2025, https://www.ebrains.eu/news-and-events/comment-in-nature-reviews-whole-brain-modelling-as-an-essential-tool-for-neuroscientists
31. Whole brain emulation by Murray Shanahan, Carlos Grande, accessed May 6, 2025, https://carlosgrande.me/whole-brain-emulation/
32. Comparative prospects of imaging methods for whole-brain ..., accessed May 6, 2025, https://pmc.ncbi.nlm.nih.gov/articles/PMC11955263/
33. Development of Brain-Inspired AGI | Columns | Mitsubishi Research Institute 50th Anniversary Website, accessed May 6, 2025, https://www.mri.co.jp/en/50th/columns/ai/no03/
34. Research - Carboncopies Foundation, accessed May 6, 2025, https://carboncopies.org/Research/
35. A REVIEW ON BLUE BRAIN TECHNOLOGY - SciSpace, accessed May 6, 2025, https://scispace.com/pdf/a-review-on-blue-brain-technology-1jvoco2i.pdf
36. Ethical Issues Related to Brain Organoid Research - PMC - PubMed Central, accessed May 6, 2025, https://pmc.ncbi.nlm.nih.gov/articles/PMC7140135/
37. Researchers simulate an entire fly brain on a laptop. Is a human brain next?, accessed May 6, 2025, https://news.berkeley.edu/2024/10/02/researchers-simulate-an-entire-fly-brain-on-a-laptop-is-a-human-brain-next/
38. Functional Tests Guide Complex "Fidelity" Tradeoffs in Whole-Brain Emulation, accessed May 6, 2025, https://jeet.ieet.org/index.php/home/article/view/152
39. BRAIN 2025: A Scientific Vision - BRAIN Initiative - National Institutes of Health (NIH), accessed May 6, 2025, https://braininitiative.nih.gov/vision/nih-brain-initiative-reports/brain-2025-scientific-vision
40. Computational modeling of whole-brain dynamics: a review of neurosurgical applications, accessed May 6, 2025, https://pubmed.ncbi.nlm.nih.gov/37382356/
41. ODIN Symposium 2025 I Speakers - Allen Institute, accessed May 6, 2025, https://alleninstitute.org/odin-symposium-2025-speakers/
42. Whole Brain Emulation: A Giant Step for Neuroscience - Tech Brew, accessed May 6, 2025, https://www.emergingtechbrew.com/stories/2019/08/15/whole-brain-emulation-giant-step-neuroscience
43. An algorithm for large-scale brain simulations - Human Brain Project, accessed May 6, 2025, https://www.humanbrainproject.eu/en/follow-hbp/news/an-algorithm-for-large-scale-brain-simulations/
44. Brain Emulation Challenge - BrainGenix, accessed May 6, 2025, https://braingenix.org/Challenge/Overview/
45. View of Functional Tests Guide Complex "Fidelity" Tradeoffs in Whole-Brain Emulation, accessed May 6, 2025, https://jeet.ieet.org/index.php/home/article/view/152/157
46. Neuromorphic Computing with Large Scale Spiking Neural ..., accessed May 6, 2025, https://www.preprints.org/manuscript/202503.1505
47. The Open Brain Institute announces the dawn of a new frontier in ..., accessed May 6, 2025, https://www.eurekalert.org/news-releases/1076968
48. Blue Brain Project ‐ EPFL, accessed May 6, 2025, https://www.epfl.ch/research/domains/bluebrain/
49. (PDF) International initiatives for the study of the human brain: EBRAINS and its Spanish node - ResearchGate, accessed May 6, 2025, https://www.researchgate.net/publication/388813248_International_initiatives_for_the_study_of_the_human_brain_EBRAINS_and_its_Spanish_node
50. EBRAINS research infrastructure secures €38 million in funding for new phase of digital neuroscience, accessed May 6, 2025, https://www.ebrains.eu/news-and-events/ebrains-research-infrastructure-secures-38-million-in-funding-for-new-phase-of-digital-neuroscience
51. Simulations - Human Brain Project, accessed May 6, 2025, https://www.humanbrainproject.eu/science-development/focus-areas/simulations/
52. Carboncopies Foundation: Home, accessed May 6, 2025, https://carboncopies.org/
53. Report from the Workshop on the Philosophy and Ethics of Brain ..., accessed May 6, 2025, https://mimircenter.org/news/report-from-the-workshop-on-the-philosophy-and-ethics-of-brain-emulation-27-28-january-2025
54. OpenWorm - Wikipedia, accessed May 6, 2025, https://en.wikipedia.org/wiki/OpenWorm
55. OpenWorm News, accessed May 6, 2025, https://openworm.org/news.html
56. [CFP(May 15th)] Toward Safe Brain-Inspired AI @ICONIP2025, accessed May 6, 2025, https://wba-initiative.org/en/25532/
57. Computational Neuroscience Resources - Fleur Zeldenrust, accessed May 6, 2025, https://fleurzeldenrust.nl/computational-neuroscience-resources/
58. www.google.com, accessed May 6, 2025, https://www.google.com/search?q=top+journals+computational+neuroscience
59. Conferences - KCNHUB, accessed May 6, 2025, https://kcnhub.com/trainings/conferences
60. Conferences - Computational Neuroscience, accessed May 6, 2025, https://compneuroweb.com/conferences.html
61. 12th International IEEE EMBS Conference on Neural Engineering (NER), accessed May 6, 2025, https://neuro.embs.org/2025/
62. International IEEE/EMBS Conference on Neural Engineering | 2266 Publications | 11336 Citations | Top Authors - SciSpace, accessed May 6, 2025, https://scispace.com/conferences/international-ieee-embs-conference-on-neural-engineering-303zpc4a
63. International Conference on Computational Methods in Systems Biology 2025 - Sciencesconf.org, accessed May 6, 2025, https://cmsb2025.sciencesconf.org/
64. American Society for Cybernetics, accessed May 6, 2025, https://asc-cybernetics.org/
65. INCF NeuroStars - Open Neuroscience, accessed May 6, 2025, https://open-neuroscience.com/en/post/incf_neurostars/
66. Best Computational Neuroscience Courses & Certificates [2025] | Coursera Learn Online, accessed May 6, 2025, https://www.coursera.org/courses?query=computational%20neuroscience
67. Bioinformatics software development: Principles and future directions - The Innovation, accessed May 6, 2025, https://www.the-innovation.org/article/doi/10.59717/j.xinn-life.2024.100083
68. Modelling and simulation software - EBRAINS, accessed May 6, 2025, https://www.ebrains.eu/modelling-simulation-and-computing/simulation/simulation-tools/
69. List of systems biology modeling software - Wikipedia, accessed May 6, 2025, https://en.wikipedia.org/wiki/List_of_systems_biology_modeling_software
70. Cognitive Computational Neuroscience - YouTube, accessed May 6, 2025, https://www.youtube.com/@cogcompneuro
71. Is Computational Neuroscience worth it?? : r/compmathneuro - Reddit, accessed May 6, 2025, https://www.reddit.com/r/compmathneuro/comments/1h0ja3i/is_computational_neuroscience_worth_it/
72. What skills should I know in order to become a Bioinformatics Software Engineer? - Reddit, accessed May 6, 2025, https://www.reddit.com/r/bioinformatics/comments/11u05kf/what_skills_should_i_know_in_order_to_become_a/
73. Any good complete books on Neuroscience/Neural Engineering for absolute beginners?, accessed May 6, 2025, https://www.reddit.com/r/neuroscience/comments/92uxz9/any_good_complete_books_on_neuroscienceneural/
74. Transitioning from Engineering to Neuroscience and Research Experience - Reddit, accessed May 6, 2025, https://www.reddit.com/r/neuroscience/comments/ep49uk/transitioning_from_engineering_to_neuroscience/
75. I'm a behavioral neuroscience undergrad. What kinds of math should I look into to be competitive in computational or cognitive neuroscience? : r/neuro - Reddit, accessed May 6, 2025, https://www.reddit.com/r/neuro/comments/613g4a/im_a_behavioral_neuroscience_undergrad_what_kinds/
76. Bioinformatics Software Development: Process, Use Cases, Insights, and More - Matellio Inc, accessed May 6, 2025, https://www.matellio.com/blog/bioinformatics-software-development/
77. A Guide to Biological Data Analysis by Exploring Bioinformatics & Databases (5 Minutes), accessed May 6, 2025, https://www.youtube.com/watch?v=42i_lF_54jk
78. bioinfo - Master of Molecular Science and Software Engineering, accessed May 6, 2025, https://msse.berkeley.edu/bioinfo/
79. Neuroscience Graduate Program Curriculum - University of Michigan Medical School, accessed May 6, 2025, https://medschool.umich.edu/interdisciplinary-programs/neuroscience-graduate-program/education/curriculum
80. Committee on Computational Neuroscience > Academic Catalog | The University of Chicago, accessed May 6, 2025, http://graduateannouncements.uchicago.edu/graduate/committeeoncomputationalneuroscience/
81. Computational Neuroscience/Modeling - Yale School of Medicine, accessed May 6, 2025, https://medicine.yale.edu/inp/research-topics/computational-neuroscience-modeling/
82. Computational Neuroscience: Mathematical and Statistical Perspectives, accessed May 6, 2025, https://www.stat.cmu.edu/~kass/papers/AnnRev2017final.pdf
83. Computational Biology Undergraduate Program - Brown CS, accessed May 6, 2025, https://cs.brown.edu/degrees/undergrad/concentrating-in-cs/concentration-requirements/cs-bi_reqs/
84. Concentrations - Biological Sciences - Carnegie Mellon University, accessed May 6, 2025, https://www.cmu.edu/bio/undergrad/academics/neuro_major/concentrations.html
85. Computational and Applied Mathematics with a Concentration in Mathematics of Data Science (MS) < Old Dominion University, accessed May 6, 2025, https://catalog.odu.edu/graduate/sciences/mathematics-statistics/computational-applied-mathematics-data-science-ms/
86. Master's and PhD in Computational Mathematical and Statistical Sciences, accessed May 6, 2025, https://www.marquette.edu/grad/programs-computational-mathematical-statistical-sciences.php
87. Theoretical and Computational Neuroscience, accessed May 6, 2025, https://www.med.upenn.edu/bgs/assets/user-content/documents/spring-2020-courses/ngg-594.pdf
88. Courses - Center for Theoretical Neuroscience - Columbia University, accessed May 6, 2025, https://ctn.zuckermaninstitute.columbia.edu/courses
89. Masters Degrees in Computational Neuroscience | FindAMasters.com, accessed May 6, 2025, https://www.findamasters.com/masters-degrees/computational-neuroscience
90. Computational Neuroscience | Carnegie Mellon University ..., accessed May 6, 2025, https://csd.cmu.edu/research/research-areas/computational-neuroscience
91. Master of Science in Artificial Intelligence - Purdue University, accessed May 6, 2025, https://www.purdue.edu/online/artificial-intelligence/
92. The Master of Science in Artificial Intelligence and Machine Learning for Engineering, accessed May 6, 2025, https://www.engr.washington.edu/admission/professional-masters-certificates/masters-artificial-intelligence-and-machine-learning
93. Programs In Cognitive Sciences, accessed May 6, 2025, https://cognitivesciencesociety.org/programs-in-cognitive-sciences/
94. MS in Applied Cognition and Neuroscience | UT Dallas, accessed May 6, 2025, https://www.utdallas.edu/fact-sheets/bbs/msf-applied-cognition-and-neuroscience/
95. AI Master's Track - Department of Computer Science, accessed May 6, 2025, https://www.cs.jhu.edu/ai-masters-track/
96. Computational Neuroscience - Neuroscience Institute - Carnegie Mellon University, accessed May 6, 2025, https://www.cmu.edu/ni/research/computational-neuroscience.html
97. Best Neuroscience Master's Programs in the USA - eStudyKit, accessed May 6, 2025, https://www.estudykit.com/study-in-usa/best-neuroscience-masters-programs-in-the-usa
98. Master Neural Systems and Computation | ETH Zurich, accessed May 6, 2025, https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/neural-systems-and-computation.html
99. 29 Neuroscience MSc degrees in Europe - Study Abroad, accessed May 6, 2025, https://www.educations.com/msc/neuroscience/europe
100. 40 Master's degrees in Neuroscience in Europe (2025) - Masterstudies.com, accessed May 6, 2025, https://www.masterstudies.com/masters-degree/neuroscience/europe
101. Master's Focus Areas & Courses - Johns Hopkins Biomedical ..., accessed May 6, 2025, https://www.bme.jhu.edu/academics/graduate/masters-programs/masters-program/masters-focus-areas-courses/
102. The Top Biomedical Engineering Master's Programs | NewEngineer, accessed May 6, 2025, https://newengineer.com/advice/the-top-biomedical-engineering-masters-programs-1154453
103. Neural Engineering - Swanson School of Engineering, accessed May 6, 2025, https://www.engineering.pitt.edu/departments/bioengineering/research/neuro/neuro/
104. 37 Master's degrees in Biomedical Engineering in Europe (2025) - Study Abroad, accessed May 6, 2025, https://www.educations.com/masters-degrees/biomedical-engineering/europe
105. accessed December 31, 1969, https://www.masterstudies.com/MSc-in-Modeling-of-Neuronal-and-Cognitive-Systems/France/Universit-Cte-dAzur/
106. Making Interdisciplinary Collaboration Work - Computer Science, accessed May 6, 2025, https://www.cs.hunter.cuny.edu/~epstein/papers/collaboration.pdf
107. NSF 24-510: Collaborative Research in Computational Neuroscience (CRCNS), accessed May 6, 2025, https://www.nsf.gov/funding/opportunities/crcns-collaborative-research-computational-neuroscience/nsf24-510/solicitation
108. Seven HCI Grand Challenges Revisited: Five-Year Progress - Taylor & Francis Online, accessed May 6, 2025, https://www.tandfonline.com/doi/full/10.1080/10447318.2025.2450411
109. Exploring Human-Like Thinking in Search Simulations with Large Language Models - arXiv, accessed May 6, 2025, https://arxiv.org/html/2504.07570v1
110. Using large language models in psychology - NSF Public Access Repository, accessed May 6, 2025, https://par.nsf.gov/servlets/purl/10575508
111. Language models and psychological sciences - PMC - PubMed Central, accessed May 6, 2025, https://pmc.ncbi.nlm.nih.gov/articles/PMC10629494/
112. Human Brain Inspired Artificial Intelligence Neural Networks - IMR Press, accessed May 6, 2025, https://www.imrpress.com/journal/JIN/24/4/10.31083/JIN26684/htm
